### ISSUE TITLE
VS Code Extension Installation Error

### ISSUE THREAD

**Issue by rehanahmedch** [ScriptPup/sqltools-teradata-driver#25]
**Describe the bug**
While installing the extension in VS Code following error occurred during installation.

Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: Error in native callback, {"code":-32603}

**Screenshots**
![Installation Error](https://github.com/ScriptPup/sqltools-teradata-driver/assets/18664811/bda7aa19-069b-4397-9ed0-1bbf595477d0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by ScriptPup** [comment]
This looks like it's the same as #24; but based on Windows.

Can you check the following:
1. What version of nodejs is you vscode running on
2. What version of vscode do you have installed

You can get both pieces of information by going to VSCode->Help->About. If you could just paste the output of the about, that may be helpful in tracking down what's going on.

Thanks,

**Comment by Fandleburg** [comment]
I'm getting the same error as @rehanahmedch .

**Desktop:**
* **OS:** Windows 11
* **Browser:** Chrome
* **nodejs version:** 16.17.1 
* **VSCode version:** 1.78.2 (user setup) (from VSCode Help->About)

**Comment by Fandleburg** [comment]
Just read through https://github.com/ScriptPup/sqltools-teradata-driver/issues/24, looks like jodejs version 16.* is the issue.
I can downgrade VSCode to version 1.77 to resolve.
I'd be interested to know if/when VSCode will be updated to use nodejs 17+.

**Comment by rehanahmedch** [comment]
> 

![image](https://github.com/ScriptPup/sqltools-teradata-driver/assets/18664811/daa45ad0-6633-4949-b252-5876e5927a11)

**Comment by starball5** [comment]
Related [question](https://stackoverflow.com/q/76626515/11107541) and [answer](https://stackoverflow.com/a/76666655/11107541) on Stack Overflow

**Comment by adamtwo** [comment]
This issue can be circumvented by setting `sqltools.useNodeRuntime` property to true. Basically, it tells SQL Tools to use an external nodejs instance to load the extension. As a result,  the extension doesn't the same memory space as Electron and avoids native errors in memory management.
I've created a PR that adds info about the workaround to the README: https://github.com/ScriptPup/sqltools-teradata-driver/pull/29

**Comment by Austin1** [comment]
Ok, just saw this and tried it, i'm still getting the same errors.

Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: No native build was found for platform=darwin arch=arm64 runtime=electron abi=108 uv=1 armv=8 libc=glibc node=18.12.1
    loaded from: /Users/[username]/.vscode/extensions/scriptpup.sqltools-teradata-driver-0.3.4/node_modules/ref-napi


Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 22.6.0

Now, coudl it be that i dont have the appropriate external nodejs instance installed or something?

```sh
node -v
```
returns v18.12.1

other errors in log:
```
{"code":-32603}
    ns: "error-handler"
[1718224482734] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
[1718224482735] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224483284] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799400] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799654] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799677] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799742] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799745] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799777] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799803] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799804] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224799805] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1718224819649] INFO  (ext): EXECUTING COMMAND => sqltools.showOutputChannel
```

**Comment by adamtwo** [comment]
I see you are running sqltools-teradata-driver 0.3.4. This version still relies on a nodejs driver that doesn't support the Mac ARM chip. Could you please update to the latest? 0.5.0 references "teradatasql": "^20.0.10" that supports Mac ARM.

**Comment by Austin1** [comment]
ok, yea, i just built from master branch manually and its working.

I don't know why my extensions page is only showing 0.3.4 and not 0.5.0. 

Super strange... if I go to the website https://marketplace.visualstudio.com/items?itemName=scriptpup.sqltools-teradata-driver

I see 0.5.0, but in my IDE, it only shows 0.3.4 when accessing marketplace. I wonder if some corporate firewall is causing this.

Well - that's on me. Looks like you all got it working. Thank you @adamtwo

**Comment by ScriptPup** [comment]
Thanks to the updates @adamtwo  contributed for 0.5.0, this should be resolved. I'm closing the issue out as it should be resolved. Let us know if you continue to have trouble!

**Comment by hfmamh** [comment]
I still have this issue after setting `sqltools.useNodeRuntime` to `true`

```
[1718735604897] ERROR (ext): ERROR: Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: \\?\c:\Users\mamirandah\.vscode\extensions\scriptpup.sqltools-teradata-driver-0.5.0-win32-x64\node_modules\ffi-napi\build\Release\ffi_bindings.node no es una aplicación Win32 válida.
```

Translation: _ffi_bindings.node isn't a valid Win32 application._
